plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1  # your AWS region
filters:
  instance-state-name: running
  tag:Name:
    - jenkins  # Update to match your tag
hostnames:
   jenkins:
     ansible_ssh_private_key_file: /Users/HP/Downloads/demo.pem


keyed_groups:
  - key: tags.Name
    prefix: tag

