plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

filters:
  instance-state-name: running
  tag:Name:
    - jenkins

hostnames:
  - public-ip-address

keyed_groups:
  - key: tags.Name
    prefix: tag
