plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1  # your AWS region
filters:
  instance-state-name: running
  tag:Name:
    - jenkins  # Update to match your tag
hostnames:
  - 13.232.235.238
keyed_groups:
  - key: tags.Name
    prefix: tag

